# Generated by Django 4.1.5 on 2023-01-13 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="status",
            field=models.CharField(
                choices=[("DRAFT", "Draft"), ("PUBLISH", "Publish")],
                default="DRAFT",
                max_length=50,
            ),
        ),
    ]
